// Softpro screen-code guideline, grouped by work function (WORK_FUNCTION_OPTIONS value).
// Sourced from IT's internal "โค้ดหน้าจอซอฟโปร" workbook — kept as a static lookup so a
// requester picking a ฟังก์ชั่นงาน sees which Softpro screens/modules it grants access to.
// The source workbook tags ~500 of its ~680 rows as generic "รายงาน"/"งานพิเศษ" instead of a
// specific work function, so those rows are excluded here rather than guessed at — this list
// is a useful starting point, not a complete one; the full workbook stays downloadable from
// the F13 page for anything not covered below.
export interface SoftproScreen {
  code: string;
  name: string;
  module: string;
}

export const SOFTPRO_GUIDELINE: Record<string, SoftproScreen[]> = {
  "งาน-ทั่วไป": [
    { code: "UC21PRQS", name: "บันทึกใบขอซื้อ", module: "PR" },
    { code: "SC26ISSU", name: "บันทึกเบิกสินค้า", module: "IC" },
    { code: "NC23PCPP", name: "บันทึกแผนการลงทุนตามโครงการ", module: "BG" },
  ],
  "งาน-IT Config": [
    { code: "WC15PJST", name: "สถานะระบบ", module: "WG" },
    { code: "WC13CRDL", name: "ประเภทเงินรับ/รายการหัก", module: "AFS" },
    { code: "WC12DOCT", name: "ประเภทการชั่ง", module: "WG" },
    { code: "WC11VHTY", name: "ประเภทยานพาหนะ", module: "WG" },
    { code: "UC15PJST", name: "สถานะระบบ", module: "PR" },
    { code: "SC15PJST", name: "สถานะระบบ", module: "IC" },
    { code: "SC13TYPE", name: "ชนิดสินค้า", module: "PR" },
    { code: "SC13TYPE", name: "ชนิดสินค้า", module: "BO" },
    { code: "SC13CLAS", name: "หมวดสินค้า", module: "IC" },
    { code: "SC13CLAS", name: "หมวดสินค้า", module: "PR" },
    { code: "SC13CLAS", name: "หมวดสินค้า", module: "BG" },
    { code: "SC12GODN", name: "แฟ้มคลังสินค้า", module: "BAS" },
    { code: "SC12GODN", name: "แฟ้มคลังสินค้า", module: "IC" },
    { code: "SC12BINL", name: "สถานที่เก็บ", module: "WG" },
    { code: "SC11CTRY", name: "ประเภทสินค้า", module: "PR" },
    { code: "SC11CTRY", name: "ประเภทสินค้า", module: "BO" },
    { code: "SC11CATY", name: "ประเภทและชนิดสินค้า", module: "IC" },
    { code: "SC11CATY", name: "ประเภทและชนิดสินค้า", module: "BG" },
    { code: "RC17RSTY", name: "กำหนดรหัสสถานะหนี้", module: "AFS" },
    { code: "RC11CATE", name: "ประเภทลูกค้า", module: "BAS" },
    { code: "OC15PJST", name: "สถานะระบบ", module: "BO" },
    { code: "NC15PJST", name: "สถานะระบบ", module: "BG" },
    { code: "NC12BGTY", name: "Type of Budget", module: "BG" },
    { code: "MC11SWST", name: "กำหนดจุดรับซื้อ", module: "AFS" },
    { code: "MC11SDIV", name: "กำหนดสาขา/โรงงาน", module: "AFS" },
    { code: "MC11DIVI", name: "ฝ่ายหรือสาขา", module: "BAS" },
    { code: "MC11DIVI", name: "Division/Branch", module: "IC" },
    { code: "MC11DIVI", name: "ฝ่าย/สาขา", module: "BG" },
    { code: "MC11DEPT", name: "แผนกและหน่วยงาน", module: "BAS" },
    { code: "MC11DEPT", name: "Departmant and Section", module: "IC" },
    { code: "MC11DEPT", name: "แฟ้มแผนก/หน่วยงาน", module: "PR" },
    { code: "MC11DEPT", name: "แผนก/หน่วยงาน", module: "BG" },
    { code: "LC11SMCT", name: "ประเภทพนักงานขาย", module: "BAS" },
    { code: "LC11SMAN", name: "แฟ้มพนักงานขาย", module: "BAS" },
    { code: "GC18ACPR", name: "กำหนดงวดการปิดบัญชี", module: "BG" },
    { code: "DC15AFST", name: "สถานะระบบ", module: "AFS" },
    { code: "AC12CATE", name: "ประเภทผู้จำหน่าย", module: "BAS" },
  ],
  "งาน-จัดซื้อ": [
    { code: "UC25REJR", name: "บันทึกคืนสินค้า", module: "PR" },
    { code: "UC24RECR", name: "บันทึกรับสินค้า", module: "PR" },
    { code: "UC23AJPO", name: "บันทึกปรับปรุงสั่งซื้อ", module: "PR" },
    { code: "UC22PORD", name: "บันทึกใบสั่งซื้อ", module: "PR" },
    { code: "UC21PRQS", name: "บันทึกใบขอซื้อ", module: "PR" },
    { code: "SC13UNIT", name: "กำหนดหน่วยวัด", module: "BAS" },
    { code: "RC14CUST", name: "แฟ้มลูกค้า", module: "BAS" },
    { code: "HC23EVLR", name: "Vendor Evaluation Record", module: "PR" },
    { code: "HC17EVLT", name: "Vendor Evaluation Table", module: "PR" },
    { code: "AC11VEND", name: "แฟ้มผู้จำหน่ายสินค้า", module: "BAS" },
    { code: "AC11VEND", name: "แฟ้มผู้จำหน่ายสินค้า", module: "PR" },
    { code: "AC11VEND", name: "แฟ้มผู้จำหน่ายสินค้า", module: "IC" },
  ],
  "งาน-บัญชี": [
    { code: "SC14PDDS", name: "แฟ้มสินค้า", module: "BAS" },
    { code: "SC14PDDS", name: "แฟ้มสินค้า", module: "IC" },
    { code: "SC14PDDS", name: "แฟ้มสินค้า", module: "PR" },
    { code: "SC14PDDS", name: "แฟ้มสินค้า", module: "BO" },
    { code: "SC13TYPE", name: "ชนิดสินค้า", module: "PR" },
    { code: "KC15REAS", name: "แฟ้มเหตุผล", module: "BAS" },
    { code: "KC13MOLD", name: "ประวัติแม่พิมพ์", module: "BAS" },
    { code: "KC11MACH", name: "แฟ้มเครื่องจักร", module: "BAS" },
  ],
  "งาน-การเงิน": [
    { code: "RC16CHER", name: "แฟ้มพนักงานเก็บเงิน", module: "BAS" },
    { code: "RC16CHER", name: "แฟ้มพนักงานการเงิน", module: "AFS" },
    { code: "RC16BKBR", name: "External Bank and Branch File", module: "BAS" },
    { code: "RC16BANK", name: "แฟ้มธนาคาร", module: "BAS" },
    { code: "RC16BANK", name: "แฟ้มบัญชีธนาคารของบริษัท", module: "AFS" },
    { code: "BC16CQPC", name: "แฟ้มทะเบียนคุมเช็ค", module: "AFS" },
  ],
  "งาน-ขาย": [
    { code: "SC20REQO", name: "Requisition Order", module: "BO" },
    { code: "RC14CUST", name: "ประวัติลูกค้า", module: "BO" },
    { code: "OC25DBNT", name: "บันทึก/แก้ไขการออกใบเพิ่มหนี้", module: "BO" },
    { code: "OC23CRNT", name: "บันทึก/แก้ไขการออกใบลดหนี้", module: "BO" },
    { code: "OC22INVO", name: "บันทึก/แก้ไข การออกใบส่งของ", module: "BO" },
    { code: "OC21ORDE", name: "บันทึก/แก้ไข Sales Order", module: "BO" },
    { code: "OC20QUOT", name: "QUOTATION (ใบเสนอราคา)", module: "BO" },
    { code: "LC18QOTA", name: "โควต้าการขาย", module: "BO" },
    { code: "LC11SMCT", name: "หมวดพนักงานขาย", module: "BO" },
    { code: "LC11SMAN", name: "แฟ้มพนักงานขาย", module: "BO" },
  ],
  "งาน-ฝ่ายไร่": [
    { code: "WC11VHTY", name: "ประเภทยานพาหนะ", module: "AFS" },
    { code: "WC11TRKW", name: "ทะเบียนรถร่วม", module: "AFS" },
    { code: "SC14LOAN", name: "กำหนดผลิตฑ์สินเชื่อ", module: "AFS" },
    { code: "RC17RSTY", name: "กำหนดรหัสสถานะหนี้", module: "AFS" },
    { code: "RC11CATE", name: "ประเภทเกษตรกร", module: "AFS" },
    { code: "MC11PVCT", name: "กำหนดจังหวัด/อำเภอ/ตำบล", module: "AFS" },
    { code: "LC16SLRT", name: "กำหนดเขตและสาย", module: "AFS" },
    { code: "LC16SLAR", name: "กำหนดโซนความรับผิดชอบ", module: "AFS" },
    { code: "LC13STCM", name: "ตารางการจ่ายเงินรางวัล", module: "AFS" },
    { code: "LC11SMAN", name: "กำหนดพนักงานส่งเสริม", module: "AFS" },
    { code: "DC18EGRD", name: "กำหนดเกรดชาวไร่", module: "AFS" },
    { code: "DC18AAGR", name: "ตารางกิจกรรมปลูก", module: "AFS" },
    { code: "DC17FMMS", name: "ประเภทแปลงปลูก", module: "AFS" },
    { code: "DC11TGYS", name: "กำหนดเป้าหมายส่งเสริมตามพนักงาน", module: "AFS" },
    { code: "DC11CPYR", name: "กำหนดปีฤดูหับ/รุ่นเพาะปลูก", module: "AFS" },
  ],
  "งาน-PR Memo": [
    { code: "UC24RRMM", name: "Memo Receiving", module: "PR" },
    { code: "UC21PMEM", name: "Memo Requistion", module: "PR" },
  ],
  "งาน-คลังพัสดุ": [
    { code: "UC24RECR", name: "บันทึกรับสินค้า", module: "PR" },
    { code: "SC29PHYA", name: "Issue Tag/Entry physical count and Approve", module: "IC" },
    { code: "SC29PHTG", name: "Edit physical tag", module: "IC" },
    { code: "SC27ADJU", name: "บันทึกปรับปรุงสินค้า", module: "IC" },
    { code: "SC26ISSU", name: "บันทึกเบิกสินค้า", module: "IC" },
    { code: "SC25TRFR", name: "บันทึกโอนสินค้าระหว่างคลัง", module: "IC" },
    { code: "SC22RETU", name: "บันทึกรับคืนสินค้า", module: "IC" },
    { code: "SC21RECT", name: "บันทึกรับสินค้า", module: "IC" },
  ],
  "งาน-คลังสินค้า": [
    { code: "SC29PHTG", name: "Edit physical tag", module: "IC" },
    { code: "SC27ADJU", name: "บันทึกปรับปรุงสินค้า", module: "IC" },
    { code: "SC26ISSU", name: "บันทึกเบิกสินค้า", module: "IC" },
    { code: "SC25TRFR", name: "บันทึกโอนสินค้าระหว่างคลัง", module: "IC" },
    { code: "SC22RETU", name: "บันทึกรับคืนสินค้า", module: "IC" },
    { code: "SC21RECT", name: "บันทึกรับสินค้า", module: "IC" },
    { code: "SC29PHYA", name: "Issue Tag/Entry physical count and Approve", module: "IC" },
  ],
  "งาน-งบประมาณ": [
    { code: "NC29AJBG", name: "Used Budget Adjustment", module: "BG" },
    { code: "NC24BGTY", name: "Entry/Approved Yearly Budget", module: "BG" },
  ],
  "งาน-ข้อมูลเกษตรกร": [
    { code: "RC14FARM", name: "แฟ้มเกษตร", module: "AFS" },
    { code: "FC21LNDC", name: "บันทึกรายการยืม/คืนเอกสาร ยกเลิกและนำกลับเกี่ยวกับหลักทรัพย์", module: "AFS" },
    { code: "FC11PROP", name: "แฟ้มหลักทรัพย์ค้ำประกัน", module: "AFS" },
    { code: "DC23CHNM", name: "ขอโอน-รับโอนโควต้า", module: "AFS" },
    { code: "DC14FRML", name: "ขึ้นทะเบียนพื้นที่ดำเนินการ", module: "AFS" },
  ],
  "งาน-สำรวจพื้นที่และขอส่งเสริม": [
    { code: "DC23CDAP", name: "ขอเพิ่ม/ลดวงเงิน", module: "AFS" },
    { code: "DC23BRSD", name: "ขออนุมัติส่งอ้อยผ่านศูนย์", module: "AFS" },
    { code: "DC21SURY", name: "สำรวจพื้นที่และข้อมูลGPS", module: "AFS" },
    { code: "DC21PQT", name: "สัญญาแจ้งอ้อย", module: "AFS" },
    { code: "DC21CPQT", name: "บันทึกสัญญาแจ้งอ้อย (ขอส่งเสริม) สำหรับดูข้อมูลเก่า", module: "AFS" },
  ],
  "งาน-เกี๊ยว": [
    { code: "DC23PYVC", name: "อนุมัติสั่งจ่ายเช็ค", module: "AFS" },
    { code: "DC23PPAY", name: "ตั้งเบิกเงินเกี้ยว", module: "AFS" },
  ],
  "งาน-เบิกจ่ายวัตถุดิบ": [
    { code: "DC22INVO", name: "บันทึกงานเบิกจ่ายวัตถุดิบ", module: "AFS" },
    { code: "DC22CRNT", name: "บันทึกการรับคืนวัตถุดิบ", module: "AFS" },
  ],
  "งาน-ติดตามหนี้": [
    { code: "DC26ARW3", name: "เปลี่ยนแปลงสถานะหนี้", module: "AFS" },
    { code: "DC26ARW2", name: "บันทึกเหตุการณ์", module: "AFS" },
    { code: "DC26ARW1", name: "แสดงหนี้คงเหลือและออกจดหมายเตือน", module: "AFS" },
  ],
  "งาน-สินเชื่อ": [
    { code: "JC22SVRT", name: "ออกใบสั่งงาน", module: "AFS" },
    { code: "DC21CPQTB", name: "บันทึกและอนุมัติขอสินเชื่อเกี๊ยวปกติ/โครงการ", module: "AFS" },
  ],
  "งาน-คำนวนและจ่ายเช็ค": [
    { code: "RC21CHRC", name: "บันทึกรับเงินจากชาวไร่", module: "AFS" },
    { code: "DC25AIIN", name: "ตั้งเรื่องจ่ายเงินค่าอ้อยอัตโนมัติ", module: "AFS" },
    { code: "DC23LPPY", name: "ตั้ง/แก้ไขเรื่องจ่ายเงินยืม/อื่นๆ", module: "AFS" },
    { code: "DC23LPAY", name: "ออกเช็คจ่ายและอนุมัติจ่ายเงินยืม/อื่นๆ", module: "AFS" },
    { code: "DC23CPPY", name: "ตั้ง/แก้ไขเรื่องจ่ายเงินค่าอ้อย", module: "AFS" },
    { code: "DC23CPAY", name: "ออกเช็คจ่ายและอนุมัติจ่ายเงินค่าอ้อย", module: "AFS" },
    { code: "DC23CDAP", name: "บันทึกเพิ่ม/ลดหนี้", module: "AFS" },
    { code: "DC23AJAP", name: "ปรับปรุงยอดหนี้", module: "AFS" },
  ],
  "งาน-บันทึกค่า CCS และการปรับค่า": [
    { code: "DC24VHRQ", name: "บันทึกปล่อยรถบรรทุกอ้อย", module: "AFS" },
    { code: "DC24VHLK", name: "ออกบัตรคิวล็อคและรายงาน", module: "AFS" },
    { code: "DC24FPWZ", name: "คำนวณปิดงวดการรับซื้อผลผลิตประจำวันจุดรับซื้อ", module: "AFS" },
    { code: "DC24FPVZ", name: "คำนวณปิดงวดการรับซื้อผลผลิตประจำวัน", module: "AFS" },
    { code: "DC24FPUR", name: "ปรับปรุงข้อมูลรับซื้อผลผลิต", module: "AFS" },
    { code: "DC24DCCS", name: "บันทึกค่า CCS หาค่าเฉลี่ยประจำวันและคำนวณเงินรับซื้อผลผลิต", module: "AFS" },
    { code: "DC11OPRC", name: "กำหนดราคารับซื้อที่จุดรับซื้อ", module: "AFS" },
    { code: "DC11CPYP", name: "ตารางปรับค่า CCS ประจำงวด", module: "AFS" },
  ],
  "งาน-สรุปปิดหีบ": [
    { code: "DU53ENDY", name: "Crop Year and End Process", module: "AFS" },
    { code: "DU51SCPY", name: "สรุปปิดหีบ", module: "AFS" },
  ],
  "งาน-ห้องชั่ง": [
    { code: "WC21WGRC", name: "บันทึกการชั่งน้ำหนักเข้า-ออกสินค้าทั่วไป", module: "WG" },
    { code: "WC21CANE", name: "บันทึกน้ำหนักชั่งหนัก", module: "WG" },
  ],
  "ผู้ปฏิบัติงาน-คิว / บัตรคิว": [
    { code: "NULL", name: "แจ้งคิว/รับใบตรวจสอบคุณภาพ", module: "WG" },
  ],
  "งาน-จ่ายน้ำมัน": [
    { code: "SC26ISSX", name: "ระบบรถโมบายน้ำมัน", module: "IC" },
    { code: "DC22UOIL", name: "บันทึกการจ่ายน้ำมันที่หัวจ่าย", module: "WG" },
  ],
  "งาน-ติดตามหนี้(AP)": [
    { code: "AC24AJAP", name: "บันทึกปรับปรุงเจ้าหนี้,", module: "AP" },
    { code: "AC22VCDN", name: "บันทึกใบลดหนี้/ใบเพิ่มหนี้,", module: "AP" },
    { code: "AC21VDIN", name: "บันทึกใบแจ้งหนี้,", module: "AP" },
  ],
  "งาน-ควบคุมการจ่ายเงิน(AP)": [
    { code: "BC24VDRC", name: "บันทึกผู้มารับเงิน,", module: "AP" },
    { code: "BC24QSAL", name: "Cheque Sale,", module: "AP" },
    { code: "BC23BKCF", name: "ยืนยันการตัดบัญชีธนาคาร,", module: "AP" },
    { code: "AC25BILL", name: "บันทึกออกใบรับวางบิล,", module: "AP" },
    { code: "AC25AIIN", name: "บันทึกเตรียมจ่ายเงินอัตโนมัติ,", module: "AP" },
    { code: "AC23PYVC", name: "ทำจ่ายเงิน,", module: "AP" },
    { code: "AC23PPAY", name: "บันทึกเตรียมจ่ายเงิน,", module: "AP" },
  ],
  "งาน-ควบคุมเงินสดย่อย(AP)": [
    { code: "AC24RUTX", name: "บันทึกกลับรายการภาษีซื้อยังไม่ครบกำหนด,", module: "AP" },
    { code: "AC23PTCZ", name: "สรุปเบิกชดเชยเงินสดย่อย,", module: "AP" },
    { code: "AC23PTCH", name: "จ่ายเงินสดย่อย,", module: "AP" },
  ],
};
